public class Exception2 {
    public static void main(String[] args) {
        
        try
        {
            int a=5/0;
        }
        catch(Exception e)
        {
            catch(ArithmeticException ae)
            {

            }
        }
        System.out.println("Helo");
    }
}
